/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function MirrorCabinetModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Model/NewDesignMirrorCabinet.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Reece_Mirror_Kado_Lussi_Mirror_Cabinet_Type_2.geometry}
        material={materials.Reece_Material_Main}
      />
      <mesh
        geometry={nodes.Reece_Mirror_Kado_Lussi_Mirror_Cabinet_Type_2_1.geometry}
        material={materials['Reece_Material-Cabinet']}
      />
      <mesh
        geometry={nodes.Reece_Mirror_Kado_Lussi_Mirror_Cabinet_Type_2_2.geometry}
        material={materials.Reece_Material_Shelf}
      />
      <mesh
        geometry={nodes.Reece_Mirror_Kado_Lussi_Mirror_Cabinet_Type_2_3.geometry}
        material={materials.Reece_Material_Secondary}
      />
    </group>
  )
}

useGLTF.preload('/Model/NewDesignMirrorCabinet.glb')
