/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/NewDesignWallPipe.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Reece_Tap_Milli_Pure_Basin_Tap_Hostess_System_160_mm_Type_1.geometry}
        material={materials.Reece_Material_Main}
      />
      <mesh
        geometry={nodes.Reece_Tap_Milli_Pure_Basin_Tap_Hostess_System_160_mm_Type_1_1.geometry}
        material={materials['Reece_Brass_Matte Black']}
      />
    </group>
  )
}

useGLTF.preload('/NewDesignWallPipe.glb')
