/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BathTubModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Model/NewDesignBathTub.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Reece_Bath_Kado_Lussi_Freestanding_Bath_Thin_Edge_Cast_Solid_Surface_Type_2.geometry}
        material={materials.Reece_Material_Main}
      />
    </group>
  )
}

useGLTF.preload('/Model/NewDesignBathTub.glb')
